rest/cms/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

rest/rest/urls.py
from django.contrib import admin
from django.urls import path,include
from cms import views
from django.conf.urls import url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^cms/', include("cms.urls")),
]

rest/cms/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
	name = models.CharField(max_length=20)
	phone_number = models.CharField(max_length=15)
	address = models.CharField(max_length=50, blank=True)

	def __str__(self):
		return self.name

class Introduce(models.Model):
	#name = models.CharField(max_length=20)
	#age = models.DecimalField(max_digits=100, decimal_places=0)
	comment = models.CharField(max_length=50)
	#sex = models.BooleanField(default=False)
	student = models.ForeignKey('Student',on_delete=models.CASCADE)


	def __str__(self):
		return self.comment

rest/cms/views.py
from django.shortcuts import render_to_response
# Create your views here.
from .models import Student, Introduce

def index(request):
	students = Student.objects.all()
	return render_to_response('cms/menu.html',locals())

rest/cms/templates/cms/menu.html
<!DOCTYPE html>
<html lang="">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Title Page</title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<h1 class="text-center">學生目錄</h1>
		<div class="container-fluid">
		{% for r in students %}
		<h2>{{ r.name }}</h2>
		{% if r.introduce_set.all %}
		<p>該學生共有{{ r.introduce_set.all|length }}筆介紹</p>
		<table class="table">
			<tr>
				<!--<th>標題</th>
				<th>年齡</th>
				<th>性別</th>-->
				<th>介紹</th>
			</tr>
			{% for introduce in r.introduce_set.all %}
			<tr>
				<!--<td>{{ introduce.name }}</td>
				<td>{{ introduce.age }}</td>
				<td>{% if introduce.sex %} 男 {% else %} 女 {% endif %}</td>-->
				<td>{{ introduce.comment }}</td>
			</tr>
			{% endfor %}
		</table>
			{% else %}
			<p>該同學啥都沒寫</p>
			{% endif %}
			{% endfor %}



	</div>
		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
 		<script src="Hello World"></script>
	</body>
</html>